### ISSUE TITLE
Include A Sum for Dice Rolls

### ISSUE THREAD

**Issue by Davnik** [TacoWolf/WolfBot#12]
Dice rolls should provide a sum after the result, likely on a new line. 

Optionally, you could also include parameters like -exalted or -shadowrun to apply rules for what classifies as a success/botch/critical.

**Comment by takouhai** [comment]
I'm not including an `-exalted` or `-shadowrun` param because I'm not too familiar with the popular dice rolling systems and I don't have time to research all of them. :unamused:
