### ISSUE TITLE
WolfBot should not order die rolls

### ISSUE THREAD

**Issue by JerryArr** [TacoWolf/WolfBot#40]
Mostly preference but it would be better if die rolls when using the die rolling function were not ordered automatically.

**Comment by takouhai** [comment]
It seems to be sorting the dice here:

```js
const r = rolllog.sort((a, b) => a - b);
```
src: https://github.com/TacoWolf/WolfBot/blob/master/scripts/dice.js#L28

I'll remove it soon.
